---
title: "Check_QC_Data"
author: "Peter Fiorica"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(DESeq2))
suppressPackageStartupMessages(library(gridExtra))
suppressPackageStartupMessages(library(ggExtra))
suppressPackageStartupMessages(library(readxl))
suppressPackageStartupMessages(library(ggrepel))
suppressPackageStartupMessages(library(DT))
suppressPackageStartupMessages(library(EnhancedVolcano))
suppressPackageStartupMessages(library(UpSetR))
suppressPackageStartupMessages(library(vsn))
library(ggforce)
"%&%"=function(a,b) paste(a,b,sep="")
arc_dir<- "/projects/rpci/songyao/pnfioric/arc_project/"
tils_dir <- "/projects/rpci/songyao/pnfioric/tils_r01_RNAseq/"

source("/projects/rpci/songyao/pnfioric/MultiEthnic_TILs_GWAS/Tractor/accessory_scripts/plotting.R")
```


```{r}
arc_dds <- readRDS("/projects/rpci/songyao/pnfioric/arc_project/data_from_li_yan/dds_Gong_Yao_QC.rds")
gene_info <- fread(tils_dir %&% "mart_export_gene_type.txt", header = T)

til_sample_info <- fread(tils_dir %&% "Phenotype_Sample_Info_wchs_nsbcs_pathways_w_tils_and_origsampetype_pam50_cibersort_iges_danaher_tcr_05092025.txt", header = T)
```


```{r load_functions}
#####
#

# DESeq Function
run_deseq_analysis <- function(count_data, 
                               col_data, # Sample information
                               gene_info, # Gene annotation File
                               design_formula) {
  # Create DESeqDataSet from matrix
  dds <- DESeqDataSetFromMatrix(countData = count_data,
                                colData = col_data, 
                                design = design_formula)
  
  # Run DESeq analysis
  dds <- DESeq(dds)
  IV <- resultsNames(dds)[2]
  print("Reporting results for expression related to: " %&% paste(IV))
  res <- results(dds, name = paste(IV))
  
  # Perform log fold change shrinkage using apeglm
  res <- lfcShrink(dds, coef = paste(IV), type = "apeglm")
  # Convert results to data.table
  output <- as.data.table(res@listData)
  output$gene_id <- res@rownames
  # Merge with gene_info
  output <- output %>% left_join(gene_info, by = c("gene_id" = "Gene stable ID version"))
  # Return the final output data.table
  return(output)
}

get_bonf_genes <-  function(dt) {
  dt %>%
    filter(pvalue < 0.05/nrow(dt)) %>%
    select(gene_id)
}
```


```{r run_DE_analysis_annotate}
arc_counts<- counts(arc_dds)
arc_coldata <- colData(arc_dds)
arc_coldata_dt <- as.data.table(colData(arc_dds)) %>% mutate(study=gsub("QC_", "", study)) %>% mutate(study = as.factor(study))
design_formula <- as.formula("~ project + race + er + study")

dds <- DESeqDataSetFromMatrix(countData = arc_counts,
                                colData = arc_coldata_dt, 
                                design = design_formula)


dds <- DESeq(dds)
IV <- resultsNames(dds)[2]
print("Reporting results for expression related to: " %&% paste(IV))
res <- results(dds, name = paste(IV))

# Perform log fold change shrinkage using apeglm
res <- lfcShrink(dds, coef = paste(IV), type = "apeglm")
# Convert results to data.table
output <- as.data.table(res@listData)
output$gene_id <- res@rownames

output <- output %>% left_join(gene_info, by = c("gene_id" = "Gene stable ID version"))

mod_mat <- model.matrix(design(dds), colData(dds))
mod_mat
```


```{r}
volcano_plot(output,
             gene_name_col = "Gene name",
             hard_threshold = 1e-7,
             threshold = 0.05/nrow(output)) +ggtitle("Gene Associated with Batch (Yao vs. Gong)\n adjusted for Race, ER, Study")
```

